/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c3",
        "on-secondary-fixed-variant": "#5a4312",
        "surface-variant": "#e8e1d8",
        "surface-dim": "#e0d9d0",
        "on-primary-container": "#94c5ee",
        "background": "#fff8f1",
        "on-tertiary-fixed": "#1b1c1a",
        "surface-container-high": "#eee7de",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#795f2b",
        "on-surface-variant": "#41474e",
        "on-error-container": "#93000a",
        "inverse-surface": "#33302a",
        "primary": "#003b5a",
        "secondary": "#745a27",
        "tertiary": "#373736",
        "outline-variant": "#c1c7cf",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001e30",
        "primary-container": "#1a5276",
        "inverse-primary": "#9bccf6",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#0e4b6e",
        "tertiary-container": "#4e4e4c",
        "tertiary-fixed": "#e4e2df",
        "surface-container": "#f4ede3",
        "on-tertiary-container": "#c1bfbd",
        "surface": "#fff8f1",
        "on-background": "#1e1b16",
        "surface-container-highest": "#e8e1d8",
        "on-surface": "#1e1b16",
        "surface-container-low": "#faf3e9",
        "error-container": "#ffdad6",
        "surface-bright": "#fff8f1",
        "primary-fixed-dim": "#9bccf6",
        "secondary-fixed": "#ffdea4",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#e4c285",
        "on-secondary-fixed": "#261900",
        "outline": "#72787f",
        "inverse-on-surface": "#f7f0e6",
        "surface-tint": "#2f6388",
        "secondary-container": "#fedb9b",
        "primary-fixed": "#cbe6ff",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "3xl": "64px",
        "lg": "24px",
        "sm": "8px",
        "xs": "4px",
        "md": "16px",
        "xl": "32px",
        "2xl": "48px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
